<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icon\road.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon\road.png" />
    <EmbeddedResource Include="icon\troll.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\r2modman\Valheim\profiles\VPOtest\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="gui_framework">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\gui_framework.dll</HintPath>
    </Reference>
<Reference Include="mscorlib">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\r2modman\Valheim\profiles\VPOtest\BepInEx\core\mscorlib.dll</HintPath>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\assembly_guiutils.dll</HintPath>
    </Reference>
    <Reference Include="assembly_postprocessing">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\assembly_postprocessing.dll</HintPath>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\assembly_utils.dll</HintPath>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\assembly_valheim.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\r2modman\Valheim\profiles\VPOtest\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\..\..\STEAM_NEW\steamapps\common\Valheim\Valheim_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>